export interface ConnectorDefinition {
  slug: string;
  name: string;
  description: string;
  type: "zapier" | "make" | "native" | "webhook";
  category: "crm" | "erp" | "communication" | "payment" | "storage" | "productivity" | "logistics" | "marketing" | "automation" | "accounting";
  authType: "oauth2" | "api_key" | "webhook";
  icon: string; // emoji
  events: string[];
}

export const CONNECTORS: ConnectorDefinition[] = [
  {
    slug: "zapier",
    name: "Zapier",
    description: "Conecte com milhares de apps via Zapier",
    type: "zapier",
    category: "productivity",
    authType: "webhook",
    icon: "⚡",
    events: ["lead.created", "deal.won", "order.created", "customer.created"],
  },
  {
    slug: "make",
    name: "Make (Integromat)",
    description: "Automações visuais avançadas",
    type: "make",
    category: "productivity",
    authType: "webhook",
    icon: "🔗",
    events: ["lead.created", "deal.won", "order.created", "customer.created"],
  },
  {
    slug: "n8n",
    name: "N8N",
    description: "Automação open-source self-hosted",
    type: "native",
    category: "productivity",
    authType: "api_key",
    icon: "🔧",
    events: ["lead.created", "lead.updated", "deal.won", "deal.lost", "order.created", "order.paid"],
  },
  {
    slug: "whatsapp",
    name: "WhatsApp API",
    description: "Envie e receba mensagens via WhatsApp",
    type: "native",
    category: "communication",
    authType: "api_key",
    icon: "💬",
    events: ["lead.created", "customer.created", "order.created"],
  },
  {
    slug: "gmail",
    name: "Gmail API",
    description: "Integre com Gmail para emails automatizados",
    type: "native",
    category: "communication",
    authType: "oauth2",
    icon: "📧",
    events: ["lead.created", "deal.won"],
  },
  {
    slug: "shopify",
    name: "Shopify",
    description: "Sincronize produtos e pedidos com Shopify",
    type: "native",
    category: "erp",
    authType: "api_key",
    icon: "🛒",
    events: ["product.updated", "order.created", "order.paid"],
  },
  {
    slug: "mercadolivre",
    name: "MercadoLivre",
    description: "Venda no MercadoLivre com sincronização",
    type: "native",
    category: "erp",
    authType: "oauth2",
    icon: "🏪",
    events: ["product.updated", "order.created"],
  },
  {
    slug: "slack",
    name: "Slack",
    description: "Notificações e alertas no Slack",
    type: "native",
    category: "communication",
    authType: "webhook",
    icon: "💼",
    events: ["deal.won", "deal.lost", "order.created", "lead.created"],
  },
  {
    slug: "stripe",
    name: "Stripe",
    description: "Processe pagamentos com Stripe",
    type: "native",
    category: "payment",
    authType: "api_key",
    icon: "💳",
    events: ["order.paid", "order.created"],
  },
  {
    slug: "hubspot",
    name: "HubSpot",
    description: "Sincronize leads e contatos com HubSpot",
    type: "native",
    category: "crm",
    authType: "api_key",
    icon: "🧲",
    events: ["lead.created", "lead.updated", "customer.created", "deal.won"],
  },
  // ── Novos conectores ──
  {
    slug: "microsoft-teams",
    name: "Microsoft Teams",
    description: "Notificações e mensagens no Microsoft Teams",
    type: "native",
    category: "communication",
    authType: "webhook",
    icon: "💜",
    events: ["deal.won", "deal.lost", "order.created", "lead.created"],
  },
  {
    slug: "google-workspace",
    name: "Google Workspace",
    description: "Integração com Google Calendar, Drive e mais",
    type: "native",
    category: "productivity",
    authType: "oauth2",
    icon: "🔵",
    events: ["lead.created", "deal.won", "customer.created"],
  },
  {
    slug: "mailchimp",
    name: "Mailchimp",
    description: "Automação de e-mail marketing",
    type: "native",
    category: "communication",
    authType: "api_key",
    icon: "🐒",
    events: ["lead.created", "customer.created"],
  },
  {
    slug: "woocommerce",
    name: "WooCommerce",
    description: "Sincronize produtos e pedidos com WooCommerce",
    type: "native",
    category: "erp",
    authType: "api_key",
    icon: "🛍️",
    events: ["product.updated", "order.created", "order.paid"],
  },
  {
    slug: "calendly",
    name: "Calendly",
    description: "Agendamento automático de reuniões",
    type: "native",
    category: "productivity",
    authType: "api_key",
    icon: "📅",
    events: ["lead.created", "deal.stage_changed"],
  },
  {
    slug: "google-sheets",
    name: "Google Sheets",
    description: "Exporte dados para planilhas Google",
    type: "native",
    category: "productivity",
    authType: "oauth2",
    icon: "📗",
    events: ["lead.created", "order.created", "customer.created"],
  },
  {
    slug: "airtable",
    name: "Airtable",
    description: "Sincronize dados com bases Airtable",
    type: "native",
    category: "productivity",
    authType: "api_key",
    icon: "📋",
    events: ["lead.created", "order.created", "customer.created"],
  },
  {
    slug: "salesforce",
    name: "Salesforce",
    description: "Integração bidirecional com Salesforce CRM",
    type: "native",
    category: "crm",
    authType: "oauth2",
    icon: "☁️",
    events: ["lead.created", "lead.updated", "deal.won", "customer.created"],
  },
  {
    slug: "twilio-sms",
    name: "Twilio SMS",
    description: "Envie SMS automatizados via Twilio",
    type: "native",
    category: "communication",
    authType: "api_key",
    icon: "📱",
    events: ["lead.created", "order.created", "customer.created"],
  },
  {
    slug: "sendgrid",
    name: "SendGrid",
    description: "E-mails transacionais e marketing via SendGrid",
    type: "native",
    category: "communication",
    authType: "api_key",
    icon: "✉️",
    events: ["lead.created", "deal.won", "order.created"],
  },
  {
    slug: "paypal",
    name: "PayPal",
    description: "Receba pagamentos via PayPal",
    type: "native",
    category: "payment",
    authType: "api_key",
    icon: "🅿️",
    events: ["order.paid", "order.created"],
  },
  {
    slug: "melhor-envio",
    name: "Melhor Envio",
    description: "Cotação e rastreio de fretes",
    type: "native",
    category: "logistics",
    authType: "api_key",
    icon: "🚚",
    events: ["order.created", "order.paid"],
  },
  {
    slug: "pipedrive",
    name: "PipeDrive",
    description: "Sincronize deals e contatos com PipeDrive",
    type: "native",
    category: "crm",
    authType: "api_key",
    icon: "🔰",
    events: ["lead.created", "deal.won", "deal.lost"],
  },
  {
    slug: "rdstation",
    name: "RD Station",
    description: "Integração com RD Station Marketing e CRM",
    type: "native",
    category: "crm",
    authType: "api_key",
    icon: "🟣",
    events: ["lead.created", "lead.updated", "customer.created"],
  },
  {
    slug: "tiny-erp",
    name: "Tiny ERP",
    description: "Gestão financeira e fiscal com Tiny ERP",
    type: "native",
    category: "erp",
    authType: "api_key",
    icon: "📘",
    events: ["order.created", "product.updated"],
  },
  {
    slug: "bling-erp",
    name: "Bling ERP",
    description: "Sincronize notas fiscais e estoque com Bling",
    type: "native",
    category: "erp",
    authType: "api_key",
    icon: "📙",
    events: ["order.created", "product.updated", "order.paid"],
  },
  {
    slug: "asaas",
    name: "Asaas",
    description: "Cobranças, boletos e Pix com Asaas",
    type: "native",
    category: "payment",
    authType: "api_key",
    icon: "💲",
    events: ["order.created", "order.paid"],
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  all: "Todos",
  crm: "CRM",
  erp: "ERP",
  communication: "Comunicação",
  payment: "Pagamento",
  productivity: "Produtividade",
  logistics: "Logística",
  marketing: "Marketing",
  automation: "Automação",
  accounting: "Contabilidade",
};
